server:
  port: 8082

spring:
  application:
    name: x-payment-adapter-app

  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: xpayment-adapter-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.iprody.xpaymentadapterapp.async.XPaymentAdapterRequestMessage"
    listener:
      ack-mode: manual
      concurrency: 1

logging:
  level:
    com.iprody.xpayment: DEBUG
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  kafka:
    topics:
      x-payment-adapter:
        request: xpayment-adapter.requests
        response: xpayment-adapter.responses
        dlt: xpayment-adapter.requests.DLT

  x-payment-provider-api:
    client:
      url: http://localhost:9999
      username: paymentAgentIprody
      password: iprodyTestPassword0123
      account: paymentAgentIprodyApiToken
